- name: 'MISCELLANEOUS : change WIRESHARK config files'
  ansible.builtin.blockinfile:
    path: '{{ item.path }}'
    block: '{{ item.block }}'
    create: true
    mode: 0644
  loop:
    - { path: '{{ ansible_env.HOME }}/.config/wireshark/preferences', block: '{{ lookup("file", "{{ playbook_dir }}/files/wireshark/preferences") }}' }
    - { path: '{{ ansible_env.HOME }}/.config/wireshark/dfilter_buttons', block: '{{ lookup("file", "{{ playbook_dir }}/files/wireshark/dfilter_buttons") }}' }
