- block:
  - name: 'APT : update & upgrade packages'
    ansible.builtin.apt:
      update_cache: true
      upgrade: safe
      autoremove: true
    become: true

  - name: 'APT : install tools'
    ansible.builtin.apt:
      name: '{{ item.name }}'
    loop:
      - { name: pipx }
      - { name: git }
      - { name: python3-pip } # for impacket
      - { name: zsh }
      - { name: terminator }
      - { name: wireshark }
      - { name: nmap }
      - { name: smbclient }
      - { name: golang-go } # for kerbrute
    become: true
