- name: 'check latest OBSIDIAN version'
  ansible.builtin.uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
    body_format: json
    return_content: true
  register: version

- name: 'install OBSIDIAN .deb file'
  ansible.builtin.apt:
    deb: 'https://github.com/obsidianmd/obsidian-releases/releases/latest/download/obsidian_{{ version.json.name }}_amd64.deb'
  become: true
