---
- name: CONFIGURE VM
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    ansible_python_interpreter: /usr/bin/python3

  vars_prompt:
    - name: git_user
      prompt: git username
      private: false

    - name: git_email
      prompt: git email
      private: false

  pre_tasks:
    - name: CONNECT & RETRIEVE ENV
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'env'

  tasks:
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/pipx.yml

    - import_tasks: tasks/github.yml
    - import_tasks: tasks/impacket.yml
    - import_tasks: tasks/obsidian.yml

    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/terminator.yml
    - import_tasks: tasks/wireshark.yml

    - import_tasks: tasks/git.yml
    - import_tasks: tasks/ssh.yml
