- name: 'SYSTEM : INSTALL : apt tools'
  ansible.builtin.apt:
    name: '{{ item.name }}'
  loop:
    - { name: pipx }
    - { name: git }
    - { name: zsh }
    - { name: terminator }
  become: true

- name: 'SYSTEM : INSTALL : check latest obsidian version'
  ansible.builtin.uri:
    url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
    body_format: json
    return_content: true
  register: version

- name: 'SYSTEM : INSTALL : obsidian .deb file'
  ansible.builtin.apt:
    deb: 'https://github.com/obsidianmd/obsidian-releases/releases/latest/download/obsidian_{{ version.json.name }}_amd64.deb'
  become: true
